{
    'name': 'NN Fund Management',
    'version': '17.0.1.0.0',
    'category': 'Accounting/Finance',
    'summary': 'Comprehensive fund management with allocations, requisitions, bills and transfers',
    'author': 'NN Services & Engineering Ltd.',
    'depends': ['base', 'mail', 'account'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'data/sequences.xml',
        'views/fund_account_views.xml',
        'views/incoming_fund_views.xml',
        'views/fund_project_views.xml',
        'views/expense_head_views.xml',
        'views/fund_allocation_views.xml',
        'views/fund_requisition_views.xml',
        'views/fund_bill_views.xml',
        'views/fund_transfer_views.xml',
        'views/menu.xml',
        'views/dashboard_views.xml',
        'views/approval_rule_views.xml',
        'views/bank_email_views.xml',
        'wizard/bank_email_test_wizard_views.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
